version: "3.3"

services:
  user-service:
    build: ./grpc-user-service # в указанной папке должен быть докер-файл
    ports:
      - 6000:6000
      - 6001:6001
      - 6002:6002
  postgres-ps:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data